services:
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/postgres
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: docker.io/postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: docker.io/redis:7-alpine
    restart: always
